CREATE TABLE genome_roles (
        genome_id INTEGER REFERENCES genomes(id) ON DELETE CASCADE ON UPDATE CASCADE,
        role_id role_id INTEGER REFERENCES roles(id) ON DELETE CASCADE ON UPDATE CASCADE,
        PRIMARY KEY (genome_id, role_id)
);
CREATE TABLE "genomes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "remarks" VARCHAR(200)   NULL,
  "sanger_id" VARCHAR(45)   NULL,
  "sanger_study_id" VARCHAR(45)   NULL,
  "species" VARCHAR(45)   NULL,
  "serotype" VARCHAR(45)   NULL,
  "site" VARCHAR(45)   NULL,
  "country_contact" VARCHAR(45)   NULL,
  "mta_agreement" VARCHAR(45)   NULL,
  "strain_id" VARCHAR(45)   NULL,
  "strain_id_sanger" VARCHAR(45)   NULL,
  "top_serotype" VARCHAR(45)   NULL,
  "top_serotype_perc" VARCHAR(25)   NULL, 
  "second_serotype" VARCHAR(45)   NULL,
  "second_serotype_perc" VARCHAR(25)   NULL,
  "mlst" VARCHAR(45)   NULL,
  "analysis_status" VARCHAR(45)   NULL,
  "analysis_comment" VARCHAR(45)   NULL,
  "gender" VARCHAR(45)   NULL,
  "age_in_years" TEXT,
  "age_in_months" TEXT,
  "body_source" VARCHAR(45)   NULL,
  "meningitis_outbreak_isolate" VARCHAR(45)   NULL,
  "hiv" VARCHAR(45)   NULL,
  "date_of_isolation" VARCHAR(20)   NULL,
  "context" VARCHAR(45)   NULL,
  "country_of_origin" VARCHAR(45)   NULL,
  "region" VARCHAR(45)   NULL,
  "city" VARCHAR(45)   NULL,
  "hospital" VARCHAR(45)   NULL,
  "latitude" FLOAT   '-1',
  "longitude" FLOAT   '-1',
  "location_country" VARCHAR(45)   NULL,
  "location_city" VARCHAR(45)   NULL,
  "cd4_count" TEXT,
  "age_category" TEXT,
  "no" TEXT,
  "lab_no" TEXT,
  "country_st" TEXT,
  "country" TEXT,
  "date_received" TEXT,
  "culture_received" TEXT,
  "sa_st" TEXT,
  "sa_penz" TEXT,
  "sa_eryz" TEXT,
  "sa_cliz" TEXT,
  "sa_tetz" TEXT,
  "sa_chlz" TEXT,
  "sa_rifz" TEXT,
  "sa_optz" TEXT,
  "sa_penmic" TEXT,
  "sa_amomic" TEXT,
  "sa_furmic" TEXT,
  "sa_cromic" TEXT,
  "sa_taxmic" TEXT,
  "sa_mermic" TEXT,
  "sa_vanmic" TEXT,
  "sa_erymic" TEXT,
  "sa_telmic" TEXT,
  "sa_climic" TEXT,
  "sa_tetmic" TEXT,
  "sa_cotmic" TEXT,
  "sa_chlmic" TEXT,
  "sa_cipmic" TEXT,
  "sa_levmic" TEXT,
  "sa_rifmic" TEXT,
  "sa_linmic" TEXT,
  "sa_synmic" TEXT
);
CREATE TABLE page_files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE,
    content_type TEXT,
    size_in_bytes INTEGER,
    file_blob BLOB
);
CREATE TABLE roles (
        id   INTEGER PRIMARY KEY,
        role TEXT
);
CREATE TABLE user_roles (
        user_id INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
        role_id INTEGER REFERENCES roles(id) ON DELETE CASCADE ON UPDATE CASCADE,
        PRIMARY KEY (user_id, role_id)
);
CREATE TABLE users (
        id            INTEGER PRIMARY KEY,
        username      TEXT,
        password      TEXT,
        email_address TEXT,
        first_name    TEXT,
        last_name     TEXT,
        active        INTEGER
);
